AWSTemplateFormatVersion: '2010-09-09'

Description: VPC

Resources:
  
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: 'andrej-vpc'
        - Key: Team
          Value: DevOps
        - Key: Project
          Value: Devops-intern

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: andrej-igw

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 'Public Subnet 1'
        - Key: Team
          Value: DevOps
        - Key: Project
          Value: Devops-intern

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 'Public Subnet 2'
        - Key: Team
          Value: DevOps
        - Key: Project
          Value: Devops-intern


  RouteTablePub:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: Name
          Value: andrej-public-rt
        - Key: Team
          Value: DevOps
        - Key: Project
          Value: Devops-intern
      VpcId: !Ref VPC
  
  RouteTableAssociationPub1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTablePub
      SubnetId: !Ref PublicSubnet1
  
  RouteTableAssociationPub2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTablePub
      SubnetId: !Ref PublicSubnet2

  InternetRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: VPCGatewayAttachment
    Properties:
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTablePub
      DestinationCidrBlock: '0.0.0.0/0'


Outputs:
  VPC:
    Description: Vpc
    Value: !Ref VPC
    Export: 
      Name: 'VPC' 

  PublicSubnet1:
    Description: Public Subnet 1 on Availability zone 1
    Value: !Ref PublicSubnet1
    Export:
      Name: 'PublicSubnet1'

  PublicSubnet2:
    Description: Public Subnet 2 on Availability zone 2
    Value: !Ref PublicSubnet2
    Export:
      Name: 'PublicSubnet2'

  
  